# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='colour',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
