# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160910_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
