# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('priority', models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, max_length=12)),
                ('speed', models.CharField(choices=[(1, 'Quick'), (2, 'Medium'), (3, 'Long')], default=2, max_length=12)),
                ('creation_time', models.DateTimeField()),
                ('response_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
