# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
