# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20161009_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='complete_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='response_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
