# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20161010_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='response_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
