# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('LAR', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencmis.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('ULN', models.CharField(blank=True, max_length=10)),
                ('house', models.CharField(blank=True, max_length=50)),
                ('road', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('town', models.CharField(blank=True, max_length=50)),
                ('post_code', models.CharField(blank=True, max_length=12)),
                ('photo', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('expected_end', models.DateField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencmis.Qualification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencmis.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='behaviour',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencmis.Student'),
        ),
    ]
