# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencmis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviour',
            name='action',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='issue',
            field=models.TextField(max_length=50),
        ),
    ]
