# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencmis', '0002_auto_20160816_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExtras',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='opencmis.Student')),
                ('NI_number', models.CharField(max_length=12)),
                ('Sexuality', models.CharField(default='Heterosexual', max_length=20)),
            ],
        ),
    ]
