# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencmis', '0003_studentextras'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineAssessment',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='opencmis.Student')),
                ('language', models.TextField()),
                ('literacy', models.TextField()),
                ('numeracy', models.TextField()),
                ('behaviour', models.TextField()),
            ],
        ),
    ]
