# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencmis', '0006_remove_ethnicity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opencmis.Ethnicity'),
        ),
    ]
