# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencmis', '0009_auto_20160912_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='opencmis.Title'),
            preserve_default=False,
        ),
    ]
