# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opencmis', '0010_student_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineHeadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField(blank=True)),
                ('presentation_blurb', models.TextField(blank=True)),
                ('behaviour_blurb', models.TextField(blank=True)),
                ('relationships_blurb', models.TextField(blank=True)),
                ('care_blurb', models.TextField(blank=True)),
                ('time_blurb', models.TextField(blank=True)),
                ('money_blurb', models.TextField(blank=True)),
                ('cooking_blurb', models.TextField(blank=True)),
                ('cleaning_blurb', models.TextField(blank=True)),
                ('laudry_blurb', models.TextField(blank=True)),
                ('travel_blurb', models.TextField(blank=True)),
                ('shopping_blurb', models.TextField(blank=True)),
                ('other_blurb', models.TextField(blank=True)),
                ('prior_blurb', models.TextField(blank=True)),
                ('comfortable_blurb', models.TextField(blank=True)),
                ('classroom_blurb', models.TextField(blank=True)),
                ('safe_blurb', models.TextField(blank=True)),
                ('skills_blurb', models.TextField(blank=True)),
                ('maths_blurb', models.TextField(blank=True)),
                ('english_blurb', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='baselineassessment',
            name='behaviour',
        ),
        migrations.RemoveField(
            model_name='baselineassessment',
            name='language',
        ),
        migrations.RemoveField(
            model_name='baselineassessment',
            name='literacy',
        ),
        migrations.RemoveField(
            model_name='baselineassessment',
            name='numeracy',
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
