# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencmis', '0013_auto_20160913_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukprn', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=10)),
            ],
        ),
    ]
