# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencmis', '0014_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'verbose_name_plural': 'Ethnicity'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
